kind: Deployment
apiVersion: apps/v1
metadata:
   name: rockykumar
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: rockykumar
   template:
      metadata:
        labels:
          app: rockykumar
      spec:
       containers:
        - name: mycontainer
          image: immortalrkr/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
