kind: Service                             
apiVersion: v1
metadata:
  name: rockykumar
  labels:
    app: rockykumar
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: rockykumar                    
  type: LoadBalancer                   
